apache/maven-dependency-analyzer

src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DefaultMethodVisitor.java, src/test/java/org/apache/maven/shared/dependency/analyzer/DefaultProjectDependencyAnalyzerTest.java, src/test/resources/typeUseAnnotationDependency/annotation/pom.xml, src/test/resources/typeUseAnnotationDependency/annotation/src/main/java/typeUseAnnotationDependency/annotation/Annotation.java, src/test/resources/typeUseAnnotationDependency/pom.xml, src/test/resources/typeUseAnnotationDependency/usage/pom.xml, src/test/resources/typeUseAnnotationDependency/usage/src/main/java/typeUseAnnotationDependency/usage/Usage.java
by implementing DefaultMethodVisitor#visitTypeAnnotation
=> [MSHARED-674] Detect Java 8 type annotations

pom.xml, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DefaultAnnotationVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DefaultClassVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DefaultFieldVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DefaultMethodVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DefaultSignatureVisitor.java
=> [MSHARED-761] Make mvn dependency:analyze work with OpenJDK 11

pom.xml
=> deps: update parent pom

src/site/apt/index.apt.vm
=> docs: rewrite for clarity

pom.xml, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DefaultClassVisitor.java
Upgrades again from 8.0.0 -> 8.0.1
Also uses the new Opcodes constant, so that the new features can actually be used.
Note: we could go to ASM9_EXPERIMENTAL to support class files with preview features as well.
Note2: I'm reusing MSHARED-870, since maven-dependency-analyzer 1.1.2 is not released yet. I'll reopen that issue.
is to use the JIRA issue title in the pull request …
=> [MSHARED-870] - Upgrade asm to 8.0.1

src/test/java/org/apache/maven/shared/dependency/analyzer/ClassFileVisitorUtilsTest.java, src/test/java/org/apache/maven/shared/dependency/analyzer/DefaultClassAnalyzerTest.java
=> use try with resources to avoid leaks

pom.xml, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DependencyClassFileVisitor.java
=> remove reference to deprecated public mutable field

pom.xml
=> [MDEP-712] update JIRA URL

src/main/java/org/apache/maven/shared/dependency/analyzer/ClassAnalyzer.java, src/main/java/org/apache/maven/shared/dependency/analyzer/DependencyAnalyzer.java, src/main/java/org/apache/maven/shared/dependency/analyzer/ProjectDependencyAnalyzer.java, src/test/java/org/apache/maven/shared/dependency/analyzer/DefaultProjectDependencyAnalyzerTest.java
=> [MDEP-753] inline deprecated field

src/main/java/org/apache/maven/shared/dependency/analyzer/DependencyAnalyzer.java, src/main/java/org/apache/maven/shared/dependency/analyzer/ProjectDependencyAnalysis.java
=> [MDEP-753] add more JavaDoc

.github/workflows/maven.yml, Jenkinsfile, pom.xml
Workaround before Maven api will be updated.
---
Due to incompatibility with newer Maven project must be built by older Maven
[Individual Contributor …
=> [MSHARED-997] Check maximum allowed Maven version

pom.xml, src/it/settings.xml
=> [MSHARED-1085] Upgrade Parent to 36

src/it/jarWithCompileScopedTestDependency/project2/pom.xml, src/it/jarWithCompileScopedTestDependency/verify.groovy, src/it/jarWithRuntimeScopedTestDependency/project2/pom.xml, src/it/jarWithRuntimeScopedTestDependency/verify.groovy, src/it/jarWithTestDependency/project2/pom.xml, src/it/jarWithTestDependency/verify.groovy, src/it/java8methodRefs/pom.xml, src/it/java8methodRefs/verify.groovy, src/it/multimoduleProject/module1/pom.xml, src/it/multimoduleProject/module1/src/main/java/foo/Main.java, src/it/setup-mock-plugin/pom.xml, src/site/site.xml
- use Maven version form project
- update dependencies in IT tests
---
[Individual Contributor License …
=> [MSHARED-1119] Cleanup IT tests

src/it/checkingNameWithTypeReferencesRequired/consumer/pom.xml, src/it/checkingNameWithTypeReferencesRequired/consumer/src/main/java/consumer/ActualImplementationClass.java, src/it/checkingNameWithTypeReferencesRequired/consumer/src/test/java/consumer/ActualImplementationClassTest.java, src/it/checkingNameWithTypeReferencesRequired/library/pom.xml, src/it/checkingNameWithTypeReferencesRequired/library/src/main/java/library/LibraryObject.java, src/it/checkingNameWithTypeReferencesRequired/pom.xml, src/it/checkingNameWithTypeReferencesRequired/provider/pom.xml, src/it/checkingNameWithTypeReferencesRequired/provider/src/main/java/provider/AbstractBaseClass.java, src/it/checkingNameWithTypeReferencesRequired/verify.groovy, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/ConstantPoolParser.java
- Handle class references in "name-and-type" entries from the constant pool
- Includes integration test based on second reproducer supplied for [MDEP-757](https://issues.apache.org/jira/browse/MDEP-757)
-----
where you replace `MDEP-757` with the appropriate JIRA issue. Best practice
If your pull request …
=> [MDEP-757] bug with "non-test scoped test only dependencies found"

src/site/xdoc/download.xml.vm
=> [MSHARED-1220] Refresh download page

.github/workflows/maven-verify.yml, pom.xml
=> [MSHARED-1205] Build on JDK 19, 20

pom.xml, src/test/java/org/apache/maven/shared/dependency/analyzer/ClassFileVisitorUtilsTest.java, src/test/java/org/apache/maven/shared/dependency/analyzer/CollectorClassFileVisitorTest.java, src/test/java/org/apache/maven/shared/dependency/analyzer/DefaultClassAnalyzerTest.java, src/test/java/org/apache/maven/shared/dependency/analyzer/ProjectDependencyAnalysisTest.java, src/test/java/org/apache/maven/shared/dependency/analyzer/ProjectDependencyAnalyzerExceptionTest.java, src/test/java/org/apache/maven/shared/dependency/analyzer/asm/ASMDependencyAnalyzerTest.java, src/test/java/org/apache/maven/shared/dependency/analyzer/asm/DependencyVisitorTest.java, src/test/java/org/apache/maven/shared/dependency/analyzer/asm/ResultCollectorTest.java
=> [MSHARED-1249] Switch to JUnit 5

pom.xml
=> [MSHARED-1250] Dependency improvements

src/main/java/org/apache/maven/shared/dependency/analyzer/CollectorClassFileVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/DefaultClassAnalyzer.java, src/main/java/org/apache/maven/shared/dependency/analyzer/DefaultProjectDependencyAnalyzer.java, src/main/java/org/apache/maven/shared/dependency/analyzer/ProjectDependencyAnalysis.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/ASMDependencyAnalyzer.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DefaultAnnotationVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DefaultClassVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DefaultFieldVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DefaultMethodVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DefaultSignatureVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DependencyClassFileVisitor.java
- Use @Override
- Use diamonds
=> Fix compiler warnings

.github/workflows/maven-verify.yml, pom.xml
https://issues.apache.org/jira/browse/MSHARED-1356
=> [MSHARED-1356] Upgrade Parent to 41

src/it/setup-mock-plugin/pom.xml
Prepare for: https://issues.apache.org/jira/browse/MPOM-467
=> Use new property for maven-plugin-tools version

pom.xml, src/it/excludeClassFromJar/pom.xml, src/it/excludeClassFromJar/src/main/java/jarWithXmlTransitiveDependency/Project.java, src/it/excludeClassFromJar/verify.groovy, src/it/excludeClassFromProject/pom.xml, src/it/excludeClassFromProject/setup.groovy, src/it/excludeClassFromProject/verify.groovy, src/it/setup-mock-plugin/src/main/java/it/test/MockAnalyzeMojo.java, src/main/java/org/apache/maven/shared/dependency/analyzer/ClassesPatterns.java, src/main/java/org/apache/maven/shared/dependency/analyzer/CollectorClassFileVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/DefaultClassAnalyzer.java, src/main/java/org/apache/maven/shared/dependency/analyzer/DefaultProjectDependencyAnalyzer.java, src/main/java/org/apache/maven/shared/dependency/analyzer/DependencyAnalyzer.java, src/main/java/org/apache/maven/shared/dependency/analyzer/ProjectDependencyAnalyzer.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DependencyClassFileVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/VisitClassException.java, src/test/java/org/apache/maven/shared/dependency/analyzer/ClassesPatternsTest.java, src/test/java/org/apache/maven/shared/dependency/analyzer/asm/ASMDependencyAnalyzerTest.java, src/test/java/org/apache/maven/shared/dependency/analyzer/asm/ResultCollectorTest.java, src/test/java/org/apache/maven/shared/dependency/analyzer/testcases/analyze/ClassToExclude.java
https://issues.apache.org/jira/browse/MSHARED-1393
=> [MSHARED-1393] Allow to exclude classes from verification

.github/dependabot.yml, pom.xml
https://issues.apache.org/jira/browse/MSHARED-1394
=> [MSHARED-1394] Upgrade Maven core dependencies to the latest and maka as provided

.github/ISSUE_TEMPLATE/BUG.yml, .github/ISSUE_TEMPLATE/FEATURE.yml, .github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md, .github/release-drafter.yml, .github/workflows/pr-automation.yml, .github/workflows/release-drafter.yml, .github/workflows/stale.yml, README.md, pom.xml
=> Enable GitHub Issues

src/main/java/org/apache/maven/shared/dependency/analyzer/asm/ConstantPoolParser.java
IntelliJ warned about this. I didn't even know it was possible to put default at beginning.
=> move default to end

src/main/java/org/apache/maven/shared/dependency/analyzer/ClassFileVisitor.java, src/main/java/org/apache/maven/shared/dependency/analyzer/ClassFileVisitorUtils.java, src/main/java/org/apache/maven/shared/dependency/analyzer/asm/DependencyClassFileVisitor.java
I think this is the best we can do without changing the public API. 
fixes #245
=> Catch exceptions on all paths
